DB_NAME = 'chartee'
DB_USER = 'scrolldev'
DB_PASSWORD = ''
DB_HOST = 'localhost'
DB_MAXCONNECTIONS = 32
DB_TRANSACTIONS_ENABLED = True

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
REDIS_PASSWORD = ''

SESSIONSDB_HOST = REDIS_HOST
SESSIONSDB_PORT = REDIS_PORT
SESSIONSDB_PASSWD = REDIS_PASSWORD
SESSIONSDB_NO = REDIS_DB
